[package]
name = "rethinkdbrust"
version = "0.0.1"
authors = ["abraaoisvi <abraao.isvi@gmail.com>", "paulo suzart <paulosuzart@gmail.com>"]

[dependencies]
rustc-serialize = "*"
byteorder = "*"

[dependencies.protobuf]
path = "/home/suzart/workspace/os/rust-protobuf"
